### ISSUE TITLE
Should we add radiomics.io as a Slicer solution on slicer.org ?

### ISSUE THREAD

**Issue by jcfr** [AIM-Harvard/SlicerRadiomics#35]
As suggested by @rkikinis , it could be listed on the top banner of https://www.slicer.org/

**Comment by fedorov** [comment]
I could never quite understand what "solution" is, but it definitely would not hurt, so I don't mind!

**Comment by jcfr** [comment]
> I could never quite understand what "solution" is,

That should help clarify: https://discourse.slicer.org/t/its-all-about-transitions-lets-talk-about-slicers-landing-page/113/35?u=jcfr

**Comment by fedorov** [comment]
@jcfr I know about the post you mentioned, but I don't think it answers the question.

But it is not important. As I said, I don't see how it could hurt, so I definitely don't mind.

**Comment by fedorov** [comment]
Sorry for not following up, my fault. Quoted from https://www.slicer.org/wiki/Slicerverse:
> If you wish to be included in the community, please send a short description, icon, institute, SlicerVerse solution name, main webpage link as well as a tutorials webpage link.

Short description: Radiomic data has the potential to uncover disease characteristics that fail to be appreciated by the naked eye. The central hypothesis of radiomics is that distinctive imaging algorithms quantify the state of diseases, and thereby provide valuable information for personalized medicine. Radiomics has emerged from oncology, but can be applied to other medical problems where a disease is imaged. 

Icon: https://raw.githubusercontent.com/Radiomics/SlicerRadiomics/master/resources/radiomics_icon.jpeg

Institute: Computational Imaging & Bioinformatics Lab - Harvard Medical School

SlicerVerse solution name: Radiomics

Main webpage link: https://www.radiomics.io/

Tutorials web page link: https://www.radiomics.io/

@jcfr please let me know if anything else is needed, or if I should send those by email to someone else.

**Comment by JoostJM** [comment]
This is already quite an old issue. @fedorov, is there still interest in adding radiomics.io on the slicer.org banner?

**Comment by fedorov** [comment]
@JoostJM in the thread above, we provided all the details as needed for radiomics.io to be included. @jcfr do you need anything else?

**Comment by jcfr** [comment]
It is a matter of submitting 2 PRs:

(1) One against the current website:
https://github.com/Slicer/slicer.org/tree/slicer-org



(2) And one against the new design:
https://github.com/Slicer/slicer.org/tree/landing-page-redesign

See https://github.com/Slicer/slicer.org/blob/landing-page-redesign/_data/solutions.yml

Thanks
J-Christophe

**Comment by fedorov** [comment]
Ok, I will make those PRs

**Comment by fedorov** [comment]
https://github.com/Slicer/slicer.org/pull/67
https://github.com/Slicer/slicer.org/pull/68

**Comment by jcfr** [comment]
Closing. SlicerRadiomics is now listed on the Slicer website.

See https://github.com/Slicer/slicer.org/blob/d0552ecf538619db502b1953f390602f031802fa/_data/solutions.yml#L41-L44
