### ISSUE TITLE
Grant maintainer access to slicer core developers

### ISSUE THREAD

**Issue by jcfr** [AIM-Harvard/SlicerRadiomics#71]
To streamline maintenance, it would be great to create a team called `slicer` with at least `maintain` access and add @lassoan , @pieper and @jcfr 

Cc: @JoostJM @fedorov

**Comment by fedorov** [comment]
@hugoaerts let me know if you are ok with this, and if so I can set up the team.

**Comment by fedorov** [comment]
@jcfr sorry this fell through the cracks. This should be all set now. Thank you for your support.

**Comment by jcfr** [comment]
@fedorov Would you mind re-inviting me so that I can be a owner ? :pray:

**Comment by fedorov** [comment]
This was done. @jcfr I also now added you as a maintainer on the pyradiomics repo - I thought this might be needed.
