### ISSUE TITLE
SlicerRadiomics extension cannot be found on mac

### ISSUE THREAD

**Issue by Mohammadreza-kosari** [AIM-Harvard/SlicerRadiomics#78]
Hello, 
I downloaded both stable and nightly versions (5.4.0 and 5.5.0) of Slicer, installed and opened the software according to the instruction. (without any problem)

But, in the extension manager I could not find "SlicerRadiomics" extension to install on my macbook air M2, Ventura 13.2.1
On the website, the "SlicerRadiomics" can be found for Linux and Windows but not Mac OS.
I would be grateful to instruct me what should I do to be able to download and use this extension.

**Comment by pieper** [comment]
it might be a packaging issue - can you look in the python console and paste any messages here?

As a fallback you can get older versions of Slicer.

**Comment by fedorov** [comment]
duplicate of #77 ... and sorry for the trouble, I have not been able to prioritize this.
